server:
  port: 8888
  
config:
  name: hello
  
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          searchLocations: classpath:/config/
          